/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Food {
  'id' : bigint,
  'expiryDate' : bigint,
  'name' : string,
  'unit' : string,
  'addedDate' : bigint,
  'quantity' : number,
  'category' : string,
}
export interface Recipe {
  'id' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'steps' : Array<string>,
  'ingredients' : Array<string>,
}
export interface _SERVICE {
  'addFood' : ActorMethod<[string, string, number, string, bigint], bigint>,
  'addRecipe' : ActorMethod<
    [string, string, Array<string>, Array<string>, Array<string>],
    bigint
  >,
  'getExpiringFoods' : ActorMethod<[bigint], Array<Food>>,
  'listFoods' : ActorMethod<[], Array<Food>>,
  'listRecipes' : ActorMethod<[], Array<Recipe>>,
  'markFoodConsumed' : ActorMethod<[bigint], undefined>,
  'recommendRecipes' : ActorMethod<[], Array<Recipe>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];