/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Food = IDL.Record({
  'id' : IDL.Nat,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'addedDate' : IDL.Int,
  'quantity' : IDL.Float64,
  'category' : IDL.Text,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'ingredients' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addFood' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getExpiringFoods' : IDL.Func([IDL.Int], [IDL.Vec(Food)], []),
  'listFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
  'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'markFoodConsumed' : IDL.Func([IDL.Nat], [], []),
  'recommendRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Food = IDL.Record({
    'id' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'addedDate' : IDL.Int,
    'quantity' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'ingredients' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addFood' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getExpiringFoods' : IDL.Func([IDL.Int], [IDL.Vec(Food)], []),
    'listFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
    'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'markFoodConsumed' : IDL.Func([IDL.Nat], [], []),
    'recommendRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };